site_name: Burton Tech
site_description: A website about my professional portfolio and tech projects 
site_url: https://ebr5.com

theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
