site_name: Burton Tech
site_description: A website about my professional portfolio and tech projects 
site_url: https://ebr5.com

theme:
  language: en
  icon:
    logo: material/nut
    repo: fontawesome/brands/github
  name: material
  features:
    - header.autohide
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: auto
      primary: green
      accent: green
      toggle:
        icon: material/brightness-auto
        name: Switch to system preferences
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

plugins:
  - search

repo_url: https://github.com/eliburtonr5/ebr5web
repo_name: eli.burtonr5/ebr5web

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eliburtonr5/ebr5web
      name: Link to eliburtonr5 GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/eliburton22/
      name: Link to eliburton22 LinkedIn
    - icon: material/email-outline
      link: mailto:eli@ebr5.com
      name: Send an email to eli@ebr5.com